### ISSUE TITLE
Firefox extension missing

### ISSUE THREAD

**Issue by treierxyz** [abn/web-eid-rpm#1]
The Firefox extension is missing from the package; the .xpi file in the RPM package is zero bytes in size.
Version: web-eid-2.3.1-8.x86_64
OS: Fedora 38

**Comment by abn** [comment]
The empty content for the xpi file is expected. 

I am using Firefox on Fedora 38 myself and I have been using the `web-eid-2.3.1-8.x86_64` package without issues. I also tested it on a LiveUSB session as well and I am unable to reproduce the issue.

Are you using Firefox via flatpak by any chance? If not is the behaviour the same even after restarting Firefox? Maybe also try checking the firefox startup logs?

**Comment by treierxyz** [comment]
> Are you using Firefox via flatpak by any chance?

No, I use Firefox installed through DNF.

> I also tested it on a LiveUSB session as well and I am unable to reproduce the issue.

That's strange. I can reproduce the issue on two machines and a live USB session. My installation steps on Fedora-KDE-Live-x86_64-38-1.6 were as follows:

1. Run the live USB
2. Add the abn/web-eid COPR repository
3. Install web-eid with DNF

Upon opening Firefox, there is no Web eID plugin to be seen. The Web eID companion app is installed and launchable. Is there a crucial step I'm missing here? ~It could also be KDE Plasma's fault.~
Edit: I tested with Fedora Workstation and had the same issue, so it's not KDE's fault.

**Comment by abn** [comment]
@treierxyz try installing the extensions from https://addons.mozilla.org/en-US/firefox/addon/web-eid-webextension/ after you have installed the native package.

Once you do this it should be available. You can verify by going to https://web-eid.eu/ and then using the `Authenticate` button.

**Comment by treierxyz** [comment]
Yes, installing the addon separately works, and I can authenticate. I can also see that you already added instructions to the README. It would be nice if the extension were available by just installing the package, but I think that is an upstream issue. Closing for now.
